テキストエディタの実装
SIT-DigiCre/digichat pull request #16
Opened 2024-12-23 07:16 UTC by newt239

# 変更内容

- チャンネルページ下部にテキスト入力欄を実装
- 絵文字ピッカーを導入

# スクリーンショット

| | |
| --- | --- |
| ![localhost_3000_(iPad Air) (1)](https://github.com/user-attachments/assets/496e393b-74ae-4198-8bec-19db69a7f210) | ![localhost_3000_(iPhone SE) (1)](https://github.com/user-attachments/assets/737571d8-8c21-4b65-aa7e-333fb95c148f) |
| ![localhost_3000_(iPad Air) (2)](https://github.com/user-attachments/assets/10af479d-e9c1-4795-8a4a-949bdb72ba9f) | ![localhost_3000_(iPhone SE) (2)](https://github.com/user-attachments/assets/4dcd9a96-3543-4166-8211-2b42a16c1877) |

# 関連Issue

close #12 

# その他

- 依存関係に変更があります
- 絵文字ピッカーの配置はβ版リリースのタイミングで意見を募集したい

2025-01-06 21:36 UTC, Meiryo7743 requested changes

2025-01-06 21:36 UTC, Meiryo7743 commented on src/components/EmojiPickerControl.tsx
> +  const isMobile = useMediaQuery("(max-width: 768px)");
`max-width: 768px` は，$x \leq 768 \space \text{px}$ を意味します。

恐らく `isMobile` は，スマートフォンのような小さな画面サイズのことを想定していると捉えました。そうなると，細かい話，例えばスクリーンサイズが `768x1024` の iPad でスマートフォンに最適化されたレイアウトが表示されてしまいます。

```suggestion
  const isMobile = useMediaQuery("(max-width: 767px)");
```

2025-01-06 21:36 UTC, Meiryo7743 commented on src/components/FileUploadControl.tsx
> +    <FileButton onChange={setFile} accept="image/png,image/jpeg" multiple>
`accept` 属性の MIME type は，もう少し許容範囲を広げて良い気がします。GIF 画像 (`image/gif`) をアップロードする需要は，意外とあっても不思議では無さそうです。

Ref. 主な MIME type の一覧
<https://developer.mozilla.org/en-US/docs/Web/HTTP/MIME_types/Common_types>

2025-01-06 23:34 UTC, newt239 commented on src/components/EmojiPickerControl.tsx
> +  const isMobile = useMediaQuery("(max-width: 768px)");
個人的には、少なくともこの実装においてiPadはモバイルと同じUIのほうが良いと考えました。タッチ操作が前提であるデバイスにおいてはPopoverよりDrawerのほうが操作しやすいと思います(Mattermostの場合はタブレットサイズだとDialogを採用しているため難しいところですが)。
この場合変数名は`isDesktop`などのほうがわかりやすいでしょうか？

(別件で、具体的にブレイクポイントとしてどの値を採用するかは共通化しておいたほうが良さそうですね)

2025-01-06 23:58 UTC, Meiryo7743 commented on src/components/EmojiPickerControl.tsx
> +  const isMobile = useMediaQuery("(max-width: 768px)");
なるほど！　確かにそれならもっともだと思います。

---

> 別件で、具体的にブレイクポイントとしてどの値を採用するかは共通化しておいたほうが良さそうですね

こちらも同意です。ブレイクポイントによる表示の出し分けは，いずれ複数の component で行う可能性が大いにあります。それゆえ，ユーティリティー関数のような形で独立させておきたいですねー。

2025-01-08 00:27 UTC, Meiryo7743 approved these changes
```plain
  _      _____ _______ __  __ 
 | |    / ____|__   __|  \/  |
 | |   | |  __   | |  | \  / |
 | |   | | |_ |  | |  | |\/| |
 | |___| |__| |  | |  | |  | |
 |______\_____|  |_|  |_|  |_|
```

2025-01-08 01:52 UTC, merged